.devcontainer/scripts/post-create-command.sh
devops/.env.sample
devops/auth.env.sample
templates/core/.env.sample

Download sample env files as part devcontainer setup.
- in devcontainer post create script, copy sample files from AzureTRE

Download sample env files in devcontainer.

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/scripts/docker-client.sh
.devcontainer/scripts/gh.sh
.devcontainer/scripts/non-root-user.sh
.devcontainer/scripts/terraform.sh
.github/actions/devcontainer_run_command/action.yml
.github/linters/.hadolint.yaml
.github/linters/.tflint.hcl
.github/pull_request_template.md
.github/scripts/clean_ci_validation_envs.sh
.github/workflows/build_validation_develop.yml
.github/workflows/clean_validation_envs.yml
.github/workflows/deploy_tre_reusable.yml
templates/core/.env.sample

Recently AzureTRE v0.4.3 was released and that needs to be reflected here.
- Update the devcontainer to fetch v0.4.3
- Update scripts and workflows to their latest version (not 1:1 but almost)
- Fixed #5 as a result

Sync with AzureTRE v0.4.3

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/scripts/porter.sh
.devcontainer/scripts/post-create-command.sh
.github/actions/devcontainer_run_command/action.yml
.github/workflows/deploy_tre.yml
.github/workflows/deploy_tre_branch.yml
.github/workflows/deploy_tre_reusable.yml
devops/.env.sample

Takes #27 and adds changes to enable the CLI to be used for deployment of shared services.

AzureTRE Release 0.5.1 alignment

---

.github/scripts/clean_ci_validation_envs.sh

Fixes #36 
Comment out and add guidance on how to use the clean validation workflow for workspaces.
- Add guidance on how to use clean validation workspaces within the clean validation workflow.
- Comment this part out  in the workflow, will add guidance in the documentation in the AzureTRE repo.

Fix clean validation workflow

---

.github/scripts/clean_ci_validation_envs.sh
.github/workflows/clean_validation_envs.yml

Fixes #40 
Use gihub repo context in clean validation environments workflow.

Use github repo context in clean validation envs.

---

README.md

Resolves #51 
Remove the configuration and upgrading part since we already point our main repo to get started and have full docs on how to set it up there.

Remove configuration

---

README.md

Remove double reference to docs.

Fix double reference

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/actions/devcontainer_run_command/action.yml
.github/scripts/clean_ci_validation_envs.sh
.github/workflows/deploy_tre.yml
.github/workflows/deploy_tre_branch.yml
.github/workflows/deploy_tre_reusable.yml
.gitignore

Upgrade to latest AzureTRE release e.g v0.9.0

Upgrade to AzureTRE release v0.9.0

---

.github/workflows/deploy_tre_reusable.yml

Fix invalid char in shared services  deployment

Fix invalid char in pipeline

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/actions/devcontainer_run_command/action.yml
.github/pull_request_template.md
.github/scripts/clean_ci_validation_envs.sh
.github/workflows/build_validation_develop.yml
.github/workflows/clean_validation_envs.yml
.github/workflows/deploy_tre.yml
.github/workflows/deploy_tre_branch.yml
.github/workflows/deploy_tre_reusable.yml
config.sample.yaml

Upgrade to latest AzureTRE release e.g v0.10.0

Upgrade to AzureTRE release v0.10.0

---

.devcontainer/devcontainer.json
.github/scripts/yarn.lock
.github/workflows/build_validation_develop.yml
.github/workflows/deploy_tre_reusable.yml

Changes to sync OSS_VERSION = 0.12.0

---

.devcontainer/devcontainer.json

Update OSS version from 0.14.0 to 0.14.1

Update Version from 0.14.0 to 0.14.1

---

.devcontainer/devcontainer.json

Fixes #91
Update OSS_VERSION to v0.15.2

Update for release 0.15.2

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Fixes #95
- Update AZ CLI version
- Update release in devcontainer.json

Update for release 0.16.0

---

.devcontainer/devcontainer.json
.github/workflows/deploy_tre.yml
.github/workflows/deploy_tre_branch.yml
.github/workflows/deploy_tre_reusable.yml

Prep for Release v0.17.0

---

.devcontainer/Dockerfile

DockerFile out of date
Update DockerFile

update dockerfile to align with AzureTRE repo 

---

.devcontainer/devcontainer.json
.github/scripts/yarn.lock
.github/workflows/deploy_tre_reusable.yml
config.sample.yaml

Update files to align with base AzureTRE.

Prep for Release v0.19.0

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/scripts/install-azure-tre-oss.sh

Adds the abilty to pull from private repos using github tokens.
- you can add a github token to the devcontainer.json. This allows the system to pull from private repos.

Added the abilty to use GitHub tokens to pull from private repos

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.github/actions/devcontainer_run_command/action.yml
.github/workflows/deploy_tre_reusable.yml

Prep for Release v0.21.0

---

.devcontainer/devcontainer.json
.github/actions/devcontainer_run_command/action.yml
.github/workflows/deploy_tre_reusable.yml

Update to release v0.24.0
